# Generated by Django 2.1.2 on 2018-10-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('raza', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=100)),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
    ]
