# Generated by Django 2.1.2 on 2018-10-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerrisDJ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='estado',
            field=models.CharField(choices=[('n', 'Seleccione un tipo'), ('r', 'Rescatado'), ('a', 'Adoptado'), ('d', 'Disponible')], default='n', max_length=20),
        ),
    ]
