# Generated by Django 2.1.2 on 2018-11-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerrisDJ', '0004_auto_20181105_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(upload_to='rescatados'),
        ),
    ]
