# Generated by Django 2.1.2 on 2018-11-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerrisDJ', '0005_auto_20181105_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(upload_to='mascotas'),
        ),
    ]
