# Generated by Django 2.1.2 on 2018-11-06 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerrisDJ', '0007_auto_20181106_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('rut', models.CharField(max_length=10)),
                ('nacimiento', models.DateField(default=datetime.date.today)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='mascota',
            name='estado',
            field=models.CharField(choices=[('', 'Seleccione un estado.'), ('r', 'Rescatado'), ('a', 'Adoptado'), ('d', 'Disponible')], default='r', max_length=1),
        ),
    ]
