# Generated by Django 2.1.2 on 2018-11-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerrisDJ', '0009_auto_20181106_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='ciudad',
            field=models.CharField(choices=[('', 'Seleccione una ciudad'), ('santiago', 'Santiago')], default='', max_length=50),
        ),
    ]
