# Generated by Django 2.1.2 on 2018-11-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerrisDJ', '0010_persona_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='region',
            field=models.CharField(choices=[('', 'Seleccione una región'), ('santiago', 'Región Metropolitana'), ('valparaiso', 'Región de Valparaiso'), ('rancagua', "Región del Libertador Bernardo O'Higgins"), ('maule', 'Región del Maule')], default='', max_length=15),
        ),
    ]
