# Generated by Django 2.1.2 on 2018-11-07 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerrisDJ', '0011_auto_20181106_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='vivienda',
            field=models.CharField(choices=[('', 'Seleccione un tipo de vivienda'), ('casa-patio-grande', 'Casa con patio grande'), ('casa-patio-pequeño', 'Casa con patio pequeño'), ('casa-sin-patio', 'Casa sin patio'), ('departamento', 'Departamento')], default='', max_length=50, verbose_name='Vivienda'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ciudad',
            field=models.CharField(choices=[('', 'Seleccione una ciudad'), ('santiago', 'Santiago')], default='', max_length=50, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nacimiento',
            field=models.DateField(default=datetime.date.today, help_text='Formato: dd/mm/aaaa', verbose_name='Fec.Nacimiento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=25, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='region',
            field=models.CharField(choices=[('', 'Seleccione una región'), ('santiago', 'Región Metropolitana'), ('valparaiso', 'Región de Valparaiso'), ('rancagua', "Región del Libertador Bernardo O'Higgins"), ('maule', 'Región del Maule')], default='', max_length=15, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rut',
            field=models.CharField(help_text='(ej: 12345678-9)', max_length=10, verbose_name='Rut'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
    ]
