# Generated by Django 2.1.2 on 2018-11-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerrisDJ', '0013_auto_20181107_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(max_length=30, verbose_name='Apellidos'),
        ),
    ]
