# Generated by Django 2.1.2 on 2018-11-07 23:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerrisDJ', '0016_auto_20181107_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^([A-Za-zÑñ\\-]{3,})[\\s]{0,1}([A-Za-zÑñ\\-]{0,})$')], verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^([A-Za-zÑñ\\-]{3,})[\\s]{0,1}([A-Za-zÑñ\\-]{0,})$')], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rut',
            field=models.CharField(help_text='(ej: 12345678-9)', max_length=10, validators=[django.core.validators.RegexValidator('^([0-9]{6,8}-[0-9Kk])$')], verbose_name='Rut'),
        ),
    ]
