# Generated by Django 2.1.2 on 2018-11-07 23:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerrisDJ', '0017_auto_20181107_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='ciudad',
            field=models.CharField(choices=[('', 'Seleccione una ciudad'), ('santiago', 'Santiago'), ('maipo', 'Isla de Maipo'), ('valparaiso', 'Valparaiso'), ('vina', 'Viña del Mar'), ('calera', 'Calera'), ('rancagua', 'Rancagua'), ('san-fernando', 'San Fernando'), ('pichilemu', 'Pichilemu'), ('talca', 'Talca'), ('linares', 'Linares'), ('parral', 'Parral')], default='', max_length=50, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rut',
            field=models.CharField(help_text='(ej: 12345678-9)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^([0-9]{6,8}-[0-9Kk])$')], verbose_name='Rut'),
        ),
    ]
