# Generated by Django 2.1.2 on 2018-11-08 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misPerrisDJ', '0018_auto_20181107_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misPerrisDJ.Mascota')),
                ('idPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misPerrisDJ.Persona')),
            ],
        ),
    ]
