# Generated by Django 2.1.2 on 2018-11-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerrisDJ', '0019_adopcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopcion',
            name='descripcion',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
