# Generated by Django 2.1.2 on 2018-11-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerrisDJ', '0020_adopcion_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcion',
            name='descripcion',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
    ]
